import os
import pandas as pd
from PIL import Image
import numpy as np
import colorsys

csv_path = '../BL6.csv'
output_root = '../images/autogenerated_datasets/color_semantic_silhouetes'

def process_csv(csv_path, output_root='../images/autogenerated_datasets/color_semantic_silhouetes'):
    # Leer CSV
    df = pd.read_csv(csv_path, sep=';')  # Usa sep='\t' si es un TSV

    def hsv_to_rgb_pixel(h, s, v):
        r, g, b = colorsys.hsv_to_rgb(h, s, v)
        return int(r * 255), int(g * 255), int(b * 255)

    for idx, row in df.iterrows():
        # Input path
        image_path = os.path.join('../',
                                "images/autogenerated_datasets/contrast_semantic_silhouetes/", #str(row['color_path_0']),
                                str(row['color_path_1']),
                                str(row['color_path_2']))
        if not os.path.exists(image_path):
            print(f'No se encuentra la imagen: {image_path}')
            continue

        # Open img
        image = Image.open(image_path).convert('RGBA')
        data = np.array(image)
        

        # HSV to RGB
        h, s, v = float(row['color_h']), float(row['color_s']), float(row['color_v'])
        rgb = hsv_to_rgb_pixel(h/100, s/100, v/100)

        # Fill silhouette (black: R=0, G=0, B=0, A>0)
        mask = (data[..., 0] == 0) & (data[..., 1] == 0) & (data[..., 2] == 0) & (data[..., 3] > 0)
        data[mask, :3] = rgb  # Change color & keeps alpha channel

        # Generate colored img
        recolored_image = Image.fromarray(data, mode='RGBA')

        # Generate output path
        output_path = os.path.join(output_root, str(row['color_path_1']), str(row['color_path_2']))
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        recolored_image.save(output_path)

        print(f"Guardada imagen: {output_path}")
