# colored_silhouettes.py
#from .utils import hsv_to_rgb_pixel
from utils import hsv_to_rgb_pixel
import os, pandas as pd, numpy as np
from PIL import Image

def generate_from_csv(csv_path, output_dir, base_input_dir = r"..\images\autogenerated_datasets\module_1_images"):
    """Genera siluetas coloreadas a partir de un CSV con rutas OJO de siluetas negras y valores HSV con los que colorear.

    ###################################################################################################
    [TODO] Hablar con Asier y valorar cómo cambiar esto para que sea transparente para el usuario
    ###################################################################################################
    """

    df = pd.read_csv(csv_path, sep=';')

    

    for idx, row in df.iterrows():
        # Nombre sin extensión
        filename_no_ext, _ = os.path.splitext(str(row['semantic_color_filename']))
        found_path = None

        # Buscar la imagen en todas las subcarpetas
        for root, dirs, files in os.walk(base_input_dir):
            if f"{filename_no_ext}.png" in files:
                found_path = os.path.join(root, f"{filename_no_ext}.png")
                # Carpeta que contiene 'silhouette'
                folder_with_silhouette = os.path.dirname(found_path)
                # Carpeta padre de 'silhouette', es decir 'objects' o 'animals'
                parent_folder = os.path.basename(os.path.dirname(folder_with_silhouette))
                break

        if found_path is None:
            print(f'Blank silhouette not found: {filename_no_ext}.png')
            continue

        # Abrir imagen
        image = Image.open(found_path).convert('RGBA')
        data = np.array(image)

        # HSV → RGB
        h, s, v = float(row['color_h']), float(row['color_s']), float(row['color_v'])
        rgb = hsv_to_rgb_pixel(h/100, s/100, v/100)

        # Rellenar silueta
        mask = (data[..., :3] == [0,0,0]).all(axis=-1) & (data[..., 3] > 0)
        data[mask, :3] = rgb

        recolored_image = Image.fromarray(data, mode='RGBA')
        
        # Guardar salida en carpeta padre + colored_silhouette
        output_path = os.path.join(output_dir, parent_folder, "colored_silhouette", f"{filename_no_ext}.png")
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        recolored_image.save(output_path)
        print(f"[COLORED SILHOUETTE]: Saved {output_path}")

def generate_from_folder(root_path, hsv_color=(0.5, 0.8, 0.9)):
    """
    Recorre recursivamente las carpetas desde root_path. Cuando encuentra una carpeta
    'silhouette', colorea todas sus imágenes con el color HSV dado y las guarda en
    una carpeta 'colored_silhouette' en la carpeta padre.
    
    Args:
        root_path (str): Ruta raíz desde donde iniciar la búsqueda.
        hsv_color (tuple): Tupla (h, s, v) con valores entre 0 y 1.
    """
    h, s, v = hsv_color
    rgb_color = hsv_to_rgb_pixel(h, s, v)

    for dirpath, dirnames, filenames in os.walk(root_path):
        if 'silhouette' in dirnames:
            silhouette_path = os.path.join(dirpath, 'silhouette')
            output_path = os.path.join(dirpath, 'colored_silhouette')
            os.makedirs(output_path, exist_ok=True)

            for fname in os.listdir(silhouette_path):
                if fname.lower().endswith(('.png', '.jpg', '.jpeg')):
                    img_path = os.path.join(silhouette_path, fname)
                    image = Image.open(img_path).convert('RGBA')
                    data = np.array(image)

                    # Crear máscara para la silueta negra
                    mask = (data[..., :3] == [0,0,0]).all(axis=-1) & (data[..., 3] > 0)
                    data[mask, :3] = rgb_color

                    recolored_image = Image.fromarray(data, mode='RGBA')
                    recolored_image.save(os.path.join(output_path, fname))

                    print(f"[COLORED SILHOUETTE]: Saved {os.path.join(output_path, fname)}")

            # Una vez procesada esta carpeta, no recorremos más al mismo nivel
            dirnames.remove('silhouette')