import os
import pandas as pd
from PIL import Image
import numpy as np
import colorsys

# Ruta al archivo CSV
csv_path = '../BL6.csv'  # <- cambia esto por la ruta real
output_root = '../images/autogenerated_datasets/color_semantic_silhouetes'

def process_csv(csv_path, output_root='../images/autogenerated_datasets/color_semantic_silhouetes'):
    # Leer CSV
    df = pd.read_csv(csv_path, sep=';')  # Usa sep='\t' si es un TSV

    # Función para convertir HSV (0–1) a RGB (0–255)
    def hsv_to_rgb_pixel(h, s, v):
        r, g, b = colorsys.hsv_to_rgb(h, s, v)
        return int(r * 255), int(g * 255), int(b * 255)

    # Procesar cada fila
    for idx, row in df.iterrows():
        # Construir ruta de entrada
        image_path = os.path.join('../',
                                "images/autogenerated_datasets/contrast_semantic_silhouetes/", #str(row['color_path_0']),
                                str(row['color_path_1']),
                                str(row['color_path_2']))
        if not os.path.exists(image_path):
            print(f'No se encuentra la imagen: {image_path}')
            continue

        # Abrir imagen
        image = Image.open(image_path).convert('RGBA')
        data = np.array(image)
        

        # Convertir HSV a RGB
        h, s, v = float(row['color_h']), float(row['color_s']), float(row['color_v'])
        rgb = hsv_to_rgb_pixel(h/100, s/100, v/100)

        # Recolorear la silueta (negra: R=0, G=0, B=0, A>0)
        mask = (data[..., 0] == 0) & (data[..., 1] == 0) & (data[..., 2] == 0) & (data[..., 3] > 0)
        data[mask, :3] = rgb  # Cambia el color manteniendo el canal alfa

        # Crear imagen nueva
        recolored_image = Image.fromarray(data, mode='RGBA')

        # Construir ruta de salida
        output_path = os.path.join(output_root, str(row['color_path_1']), str(row['color_path_2']))
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        # Guardar imagen
        recolored_image.save(output_path)

        print(f"Guardada imagen: {output_path}")
